backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# save draft: commits to new branch
# edit draft: pushes another commit to draft branch / PR
# approve and publish draft: merges PR and deletes branch
publish_mode: editorial_workflow

# path where uploaded files are saved, relative to base repo
media_folder: "images/uploads"

# path where media library files will be accessed, relative to base of built site
# defaults to media_folder
# public_folder

# ?
# media_library

# url to published site
site_url: https://www.brooklineequitycoalition.org/

# link to main site in CMS header
# display_url

# logo on cms login page
logo_url: https://www.brooklineequitycoalition.org/img/coalition/logo.svg

i18n:
  structure: multiple_folders
  locales: [en, es, zh]

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "Here's a description"
    folder: "_pages"
    create: true
    extension: "json"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { slug: "Slug", name: "slug", widget: "string", i18n: true }
